import {displayMode} from './display-mode.mjs';
import {ScriptReview} from './script-review.js';
import {CueAudio} from './cue-audio.mjs';
import {PresenterSync} from './presenter-sync.js';
import {firstBuild,visibleBuild,buildCount,slideAtStep} from './text-build.mjs';
import {PointerOverlay} from './pointer-overlay.js';
import {AgintelFlow} from './agintel-flow.js';
import {GlobePanel} from './globe-panel.js';
import {globeOwnsKey} from './globe-options.mjs';
import {SceneControls,sceneActions} from './scene-controls.mjs';
import {SceneRenderer} from './renderer.js';import {viewDefaults,viewFields,cameraState,validateSlide,clone} from './model.mjs';import {scenes} from './scenes/index.js';import {slideKey,slideLabel,findSlide,adjacentSlide} from './navigation.mjs';
const $=q=>document.querySelector(q),key='newheat-slide-studio-v005-drafts';
const projectLink=document.createElement('a');projectLink.id='project-link';projectLink.target='_blank';projectLink.rel='noopener noreferrer';projectLink.hidden=true;
const projectLinkHost=document.createElement('span');projectLinkHost.className='project-link-host';projectLinkHost.textContent='GitHub';
const projectLinkLabel=document.createElement('span'),projectLinkArrow=document.createElement('span');projectLinkArrow.textContent='↗';projectLinkArrow.setAttribute('aria-hidden','true');projectLink.append(projectLinkHost,projectLinkLabel,projectLinkArrow);$('#stage').append(projectLink);
const agintelFlow=new AgintelFlow($('#media-layer'));agintelFlow.onNavigate=direction=>step(direction);
function renderProjectLink(){const link=slideAtStep(current(),revealStep).scene.projectLink;projectLink.hidden=!link;if(link){const github=new URL(link.url).hostname==='github.com';projectLink.href=link.url;projectLinkHost.textContent=github?'GitHub':new URL(link.url).hostname;projectLinkLabel.textContent=link.label;projectLink.setAttribute('aria-label','Open '+link.label+(github?' on GitHub':' website'))}}
let entries=[],drafts=new Map(),number=1,selected=null,tab='camera',presenting=displayMode(location.search).presenting,reviewing=displayMode(location.search).reviewing,continuous=false,clock=0,last=performance.now(),saving=false,mediaSignature='',wakeTimer,revealStep=0,sceneClock=0,scenePaused=false;
try{drafts=new Map(Object.entries(JSON.parse(localStorage.getItem(key)||'{}')))}catch{}
const entry=()=>entries.find(e=>slideKey(e.slide)===String(number)),current=()=>drafts.get(entry()?.slide.id)?.slide||entry()?.slide;
const liveControls=new SceneControls();
const cueAudio=new CueAudio({onChange:state=>{const button=$('#cue-audio');button.hidden=!state.available;button.textContent=state.playing?'Pause audio':'Play audio';}});
const presentationSync=new PresenterSync(()=>entry()?{id:entry().slide.id,step:revealStep,presenting}:null);
const scriptReview=new ScriptReview($('#script-review'),{onClose:()=>setReview(false),onNavigate:n=>{go(n);presentationSync.send(true)},onStep:step,onBoost:boostScene,onPhone:showPhoneScript});
const revealCount=()=>buildCount(current());
function syncReveals(){const total=revealCount(),editing=!presenting&&tab==='text';for(const t of slideAtStep(current(),revealStep)?.overlays||[]){const el=document.querySelector('[data-overlay="'+t.id+'"]');if(!el)continue;const hidden=!visibleBuild(t,{slide:current(),step:revealStep,editing,selected});el.classList.toggle('build-hidden',hidden);el.setAttribute('aria-hidden',String(hidden))}$('#reveal-controls').hidden=!total;$('#reveal-status').textContent=editing?(current().scene.textBuild==='replace'?'Editing selected stanza':'Editing all '+total+' lines'):revealStep+' / '+total+' lines · Next to reveal';$('#present-count').textContent=slideLabel(entry().slide)+(entry().optional?' · Optional':' · '+(entries.filter(e=>!e.optional).findIndex(e=>e.slide.id===entry().slide.id)+1)+' / '+entries.filter(e=>!e.optional).length)+(total?' · '+revealStep+'/'+total:'');for(const id of ['next','present-next'])$('#'+id).setAttribute('aria-label',revealStep<total?'Reveal next line':'Next slide');scriptReview.render(entries,current(),revealStep,sceneActions[current()?.scene.preset]);presentationSync.send()}
function step(direction){const total=revealCount();if((direction>0&&revealStep<total)||(direction<0&&revealStep>firstBuild(current()))){if(!presenting&&tab==='text')showTab('camera');revealStep+=direction;clock=0;if(current().scene.afterMedia)renderStage(false);else syncReveals();presentationSync.send(true);return}go(slideKey(adjacentSlide(entries,entry().slide.id,direction).slide),{reveal:direction<0?'all':0});presentationSync.send(true)}
function message(text,error=false){$('#message').textContent=text;$('#message').classList.toggle('error',error)}
function retain(){localStorage.setItem(key,JSON.stringify(Object.fromEntries(drafts)))}
function editable(){const e=entry();if(!drafts.has(e.slide.id))drafts.set(e.slide.id,{slide:clone(e.slide),revision:e.revision});return drafts.get(e.slide.id).slide}
function badges(){const dirty=drafts.has(entry()?.slide.id);$('#save-state').textContent=dirty?'Unsaved changes':'Saved to disk';$('#save-state').classList.toggle('dirty',dirty);$('#save').disabled=saving||!dirty;$('#save').textContent=saving?'Saving…':'Save slide '+slideLabel(entry().slide);document.querySelectorAll('.slide-link').forEach(a=>{a.querySelector('.dot').textContent=drafts.has(a.dataset.id)?'•':''})}
function changed(){retain();badges();message('');}
const renderer=new SceneRenderer($('#gpu'),(state,interaction)=>{if(presenting)return;const d=editable();d.view.state=state;changed();syncCamera();if(interaction?.save)message('Live camera copied to the slide. Save slide 13 to keep it.')},(text,error)=>{if(error)message('Canvas: '+text,true)});
const captureCamera=document.createElement('button');captureCamera.id='capture-live-camera';captureCamera.className='wide';captureCamera.textContent='Use live camera in slide';captureCamera.hidden=true;captureCamera.onclick=()=>renderer.savePlayCamera();$('#reset-camera').after(captureCamera);
const globePanel=new GlobePanel($('#stage'),renderer);const pointerOverlay=new PointerOverlay($('#stage'));renderer.onPlayState=()=>{globePanel.sync();pointerOverlay.sync(renderer)};
function syncSlidePosition(){const target=entry();if(!target)return;$('#slide-number').textContent='SLIDE '+slideLabel(target.slide)+(target.optional?' · OPTIONAL':' · '+(entries.filter(e=>!e.optional).findIndex(e=>e.slide.id===target.slide.id)+1)+' OF '+entries.filter(e=>!e.optional).length);}
function navigation(){$('.sidebar-heading span').textContent=entries.filter(e=>!e.optional).length+' + '+entries.filter(e=>e.optional).length;const list=$('#slide-list');list.replaceChildren();let optional=false;for(const e of entries){if(e.optional&&!optional){const label=document.createElement('div');label.className='sidebar-section';label.textContent='Optional · direct access';list.append(label);optional=true}const a=document.createElement('a');a.href='#'+slideKey(e.slide);a.className='slide-link';a.dataset.id=e.slide.id;a.setAttribute('aria-current',String(slideKey(e.slide)===String(number)));a.title='Slide '+slideLabel(e.slide)+' · '+e.slide.title;const n=document.createElement('span');n.className='num';n.textContent=slideLabel(e.slide);const title=document.createElement('span');title.className='name';title.textContent=e.slide.title;const dot=document.createElement('span');dot.className='dot';a.append(n,title,dot);list.append(a)}}
function fit(){const r=$('#preview-area').getBoundingClientRect(),scale=Math.min(r.width/1280,r.height/720);$('#stage').style.transform=`translate(-50%,-50%) scale(${scale})`}
new ResizeObserver(fit).observe($('#preview-area'));
function showTab(next){tab=next;for(const name of ['camera','text','notes']){$('#'+name+'-tab').setAttribute('aria-selected',String(name===tab));$('#'+name+'-panel').hidden=name!==tab}renderInspector()}
function textStyle(el,t){Object.assign(el.style,{left:t.x+'px',top:t.y+'px',width:t.width+'px',fontSize:t.size+'px',fontFamily:t.font,fontWeight:t.font==='Roboto Black'?900:400,color:t.color,textAlign:t.align})}
function renderOverlays(){const layer=$('#text-layer');layer.replaceChildren();for(const t of slideAtStep(current(),revealStep).overlays){const el=document.createElement('div');el.className='overlay'+(t.id===selected&&tab==='text'?' selected':'')+(t.font==='Roboto'?' body-text':'')+(t.bullet?' bullet':'');el.dataset.overlay=t.id;if(t.reveal)el.dataset.reveal=t.reveal;el.textContent=t.text;textStyle(el,t);el.addEventListener('pointerdown',e=>{
  if(presenting)return;e.preventDefault();e.stopPropagation();selected=t.id;showTab('text');document.querySelectorAll('.overlay').forEach(x=>x.classList.toggle('selected',x.dataset.overlay===selected));
  const scale=$('#stage').getBoundingClientRect().width/1280,start={x:e.clientX,y:e.clientY,tx:t.x,ty:t.y};el.setPointerCapture(e.pointerId);
  const move=ev=>{const o=editable().overlays.find(x=>x.id===selected);o.x=Math.max(0,Math.min(1280-o.width,start.tx+(ev.clientX-start.x)/scale));o.y=Math.max(0,Math.min(680,start.ty+(ev.clientY-start.y)/scale));textStyle(el,o);$('#text-x').value=Math.round(o.x*100)/100;$('#text-y').value=Math.round(o.y*100)/100;changed()};
  const up=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up)};el.addEventListener('pointermove',move);el.addEventListener('pointerup',up);
 });layer.append(el)}syncReveals()}
function position(el,f){Object.assign(el.style,{left:f.x+'px',top:f.y+'px',width:f.width+'px',height:f.height+'px'})}
function renderMedia(){const d=slideAtStep(current(),revealStep),signature=JSON.stringify([d.id,d.kind,d.scene,d.view.frame]);if(signature===mediaSignature)return;mediaSignature=signature;
 const layer=$('#media-layer');cueAudio.setCue(d.scene.audioLoop);$('#film-play').hidden=true;$('#text-layer').hidden=false;document.body.classList.toggle('live-embed',!!d.scene.embed);document.body.classList.toggle('thor-demo',d.scene.embed==='http://127.0.0.1:5178/');document.body.classList.toggle('oasis-demo',d.scene.embed==='http://127.0.0.1:8085/oasis');document.body.classList.toggle('poem-slide',d.scene.textBuild==='replace');document.body.classList.toggle('film-cue',d.kind==='film');
 layer.querySelectorAll('video').forEach(v=>v.pause());
 if(agintelFlow.show(d,entries.find(e=>e.slide.id==='slide-10').slide,entries.find(e=>e.slide.id==='slide-11').slide))return;
 layer.querySelectorAll('video').forEach(v=>v.pause());layer.replaceChildren();
 if(d.kind==='cover'||d.kind==='flame'){if(d.kind==='flame'){const flame=document.createElement('img');flame.src='/assets/flame.gif';flame.className='artwork';flame.style.width='1280px';flame.style.height='720px';flame.style.objectFit='cover';flame.alt='Living NEWHEAT flame';layer.append(flame)}const logo=document.createElement('img');logo.src=d.kind==='cover'?'/assets/wordmark-amber.svg':'/assets/logo.png';logo.alt='NEW HEAT';logo.className='artwork';position(logo,d.kind==='cover'?{x:250,y:322,width:780,height:76}:{x:330,y:329,width:620,height:62});layer.append(logo)}
 if(d.kind==='film'){const v=document.createElement('video');v.src='/assets/film.mp4';v.className='original-video';v.id='closing-film';v.muted=false;v.defaultMuted=false;v.volume=1;v.playsInline=true;v.preload='metadata';v.hidden=true;v.onended=()=>go(25);v.onerror=()=>message('The closing film could not load.',true);layer.append(v);$('#film-play').hidden=false;return}
 if(d.scene.embed){const frame=document.createElement('iframe');frame.src=d.scene.embed;frame.title=d.scene.label;frame.className='live-demo';frame.allow=d.scene.embed==='http://127.0.0.1:5178/'?'camera; fullscreen':'fullscreen';frame.referrerPolicy='no-referrer';position(frame,d.view.frame);layer.append(frame);const link=document.createElement('a');link.href=d.scene.embed==='http://127.0.0.1:8085/oasis'?'https://newheat.co/oasis':d.scene.embed;link.target='_blank';link.rel='noopener noreferrer';link.className='demo-open';link.textContent=d.scene.embed==='http://127.0.0.1:5178/'?'Open thor.gl ↗':d.scene.embed==='http://127.0.0.1:8085/oasis'?'newheat.co/oasis ↗':'Open TreeLayer ↗';if(d.scene.embed!=='http://127.0.0.1:5178/')layer.append(link);return}
 if(d.scene.gallery){const gallery=document.createElement('div');gallery.className='version-gallery';position(gallery,d.view.frame);for(const item of d.scene.gallery){const figure=document.createElement('figure'),img=document.createElement('img'),caption=document.createElement('figcaption');img.src='/'+item.src;img.alt=item.alt;caption.textContent=item.label;figure.append(img,caption);gallery.append(figure)}layer.append(gallery);return}
 if(d.scene.linkPreview){const a=document.createElement('a'),img=document.createElement('img'),c=d.scene.linkPreview.crop;a.href=d.scene.linkPreview.url;a.target='_blank';a.rel='noopener noreferrer';a.className='linked-preview';a.setAttribute('aria-label','Open WSJ video preview in a new tab');position(a,d.view.frame);img.src='/'+d.scene.media;img.alt=d.scene.label;Object.assign(img.style,{width:c.imageWidth/c.width*100+'%',left:-c.x/c.width*100+'%',top:-c.y/c.height*100+'%'});const cue=document.createElement('span');cue.textContent='View on WSJ ↗';a.append(img,cue);layer.append(a);return}
 if(d.scene.media){const video=/\.(mp4|webm)$/.test(d.scene.media),el=document.createElement(video?'video':'img');el.src='/'+d.scene.media;el.className='artwork';el.style.objectFit=d.scene.fit||'contain';el.style.objectPosition=(d.scene.position||[50,50]).map(v=>v+'%').join(' ');if(!video)el.alt=d.scene.label||'';position(el,d.view.frame);if(video){const manual=d.scene.playback==='manual';el.muted=false;el.defaultMuted=false;el.volume=1;el.playsInline=true;el.autoplay=!manual;el.preload='metadata';el.controls=true;el.loop=false;el.classList.add('demo-video');
  const resume=document.createElement('button');resume.className='playback-resume';resume.textContent='Play with sound';Object.assign(resume.style,{left:(d.view.frame.x+d.view.frame.width/2)+'px',top:(d.view.frame.y+d.view.frame.height/2)+'px'});
  const play=async()=>{if(!el.isConnected)return;try{await el.play();if(!el.isConnected){el.pause();return}resume.remove()}catch(error){if(el.isConnected&&error.name!=='AbortError')layer.append(resume)}};
  resume.onclick=()=>{el.muted=false;el.volume=1;void play()};el.onplay=()=>resume.remove();el.onloadedmetadata=()=>{if(!manual)void play()};el.onerror=()=>message('This video could not load.',true)}layer.append(el);if(d.scene.scrim==='bottom'){const scrim=document.createElement('div');scrim.className='photo-scrim';position(scrim,d.view.frame);layer.append(scrim)}}
 else if(d.scene.preset==='placeholder'){const well=document.createElement('div');well.className='media-placeholder';position(well,d.view.frame);well.textContent=d.scene.label||'Original media';layer.append(well)}
}
function renderStage(animate=false){const d=current();$('#stage').style.background=d.background;renderOverlays();renderMedia();renderProjectLink();renderer.set(d,{animate,time:sceneClock,controls:liveControls.snapshot()});globePanel.sync();captureCamera.hidden=!renderer.playground;syncAnimation();$('#scene-state').textContent=d.view.type+' · '+(d.kind==='film'?'Closing film':scenes[d.scene.preset].label)+' · 1280 × 720';}
function syncCamera(){const d=current();if(!d)return;for(const k of viewFields[d.view.type]){const input=$('#camera-'+k);if(input&&document.activeElement!==input)input.value=Array.isArray(d.view.state[k])?d.view.state[k].join(', '):Math.round(d.view.state[k]*1e6)/1e6}if(document.activeElement!==$('#camera-json'))$('#camera-json').value=JSON.stringify(d.view.state,null,2)}
function numericFields(container,fields,values,onChange,prefix){container.replaceChildren();for(const k of fields){const label=document.createElement('label');label.textContent=k;const input=document.createElement('input');input.type=k==='target'?'text':'number';input.step='any';input.id=prefix+k;input.value=Array.isArray(values[k])?values[k].join(', '):values[k];if(k==='target')label.className='target';input.addEventListener('input',()=>{let value=k==='target'?input.value.split(',').map(x=>Number(x.trim())):input.valueAsNumber;if(k==='target'?(value.length!==3||value.some(x=>!Number.isFinite(x))):!Number.isFinite(value))return;onChange(k,value)});label.append(input);container.append(label)}}
function cameraEdit(fn){const candidate=clone(current());fn(candidate);try{validateSlide(candidate);editable().view=candidate.view;editable().scene=candidate.scene;changed();renderer.set(current());syncCamera();renderMedia()}catch(e){message(e.message,true)}}
function renderInspector(){const d=current();if(!d)return;$('#view-type').value=d.view.type;
 $('#scene-preset').replaceChildren(...Object.entries(scenes).map(([value,s])=>{const o=document.createElement('option');o.value=value;o.textContent=s.label;return o}));$('#scene-preset').value=d.scene.preset;
 $('#scene-hint').textContent=scenes[d.scene.preset].description||(d.scene.preset==='placeholder'?'This original media slot is still open. Choose a reference scene to frame its camera.':d.scene.preset==='globe'?'Public Natural Earth geometry. Drag or scroll the globe, or enter an exact viewState.':d.scene.preset==='grid'?'Reference axes for an OrbitView. Drag to rotate and scroll to zoom.':'Camera is saved even while the canvas is empty.');
 numericFields($('#camera-fields'),viewFields[d.view.type],d.view.state,(k,v)=>cameraEdit(s=>{s.view.state[k]=v}),'camera-');
 numericFields($('#frame-fields'),['x','y','width','height'],d.view.frame,(k,v)=>cameraEdit(s=>{s.view.frame[k]=v}),'frame-');syncCamera();
 $('#background').value=d.background;$('#duration').value=d.duration??'';$('#duration').disabled=['film','flame','black'].includes(d.kind);$('#edit-title').value=d.title;$('#notes').value=d.notes;const poem=d.scene.textBuild==='replace';$('#phone-cue-fields').hidden=poem;$('#poem-phone-hint').hidden=!poem;$('#speaker-mode').value=d.speaker?.mode||'cues';$('#speaker-points').value=(d.speaker?.points||[]).join('\n');$('#speaker-exact').value=d.speaker?.text||'';$('#speaker-exact-field').hidden=d.speaker?.mode!=='exact';const links=$('#source-links');links.replaceChildren();for(const source of entry().sourceLinks||[]){const a=document.createElement('a');a.href=source.url;a.textContent=source.label;a.target='_blank';a.rel='noopener noreferrer';links.append(a)}$('#source-links-section').hidden=!links.children.length;
 if(!d.overlays.some(x=>x.id===selected))selected=d.overlays[0]?.id||null;
 const sel=$('#overlay-select');sel.replaceChildren(...d.overlays.map((t,i)=>{const o=document.createElement('option');o.value=t.id;o.textContent=String(i+1).padStart(2,'0')+' · '+(t.text.split('\n')[0]||'Empty text');return o}));sel.value=selected||'';$('#overlay-controls').hidden=!selected;syncText();
}
function syncText(){const t=current()?.overlays.find(x=>x.id===selected);if(!t)return;$('#overlay-text').value=t.text;for(const [id,k] of [['x','x'],['y','y'],['width','width'],['size','size'],['font','font'],['color','color'],['align','align']])$('#text-'+id).value=t[k]}
function syncAnimation(){
 const preset=current()?.scene.preset,scene=scenes[preset],action=sceneActions[preset];
 $('#animation-controls').hidden=!scene?.animated;$('#live-controls').hidden=!action;
 for(const id of ['scene-up','scene-down','present-up','present-down']){$('#'+id).hidden=!action;if(action){const up=id.endsWith('up');$('#'+id).title=(up?'↑ ':'↓ ')+action[up?'up':'down'];$('#'+id).setAttribute('aria-label',action[up?'up':'down']);}}
 if(action){$('#scene-action').textContent='↑ '+action.up+' · ↓ '+action.down;$('#scene-value').textContent=preset==='shiny-globe'?'Shine ×'+liveControls.shineTarget:preset==='connections'?(renderer.parent.dataset.arcCount||'480')+' connections':'Clock ×'+liveControls.clockSpeed;}
 if(!scene?.animated)return;
 const progress=preset==='connections'?liveControls.connectionTime:sceneClock;
 $('#animation-time').max=scene.duration;$('#animation-time').value=Math.min(progress,scene.duration);$('#animation-time').setAttribute('aria-label',preset==='connections'?'Connection removal progress':'Animation time');
 $('#animation-readout').textContent=preset==='connections'?Math.round(progress/20*100)+'% removed':Math.min(sceneClock,scene.duration).toFixed(1)+' s';$('#animation-play').textContent=scenePaused?'Play':'Pause';
}
function resetAnimation(){sceneClock=0;scenePaused=false;liveControls.reset();renderer.resetRotation();last=performance.now();renderer.draw(0,liveControls.snapshot());syncAnimation()}
function boostScene(direction){const preset=current()?.scene.preset;if(!sceneActions[preset])return false;liveControls.boost(preset,direction);syncAnimation();return true}
function go(n,{animate=presenting,reveal=0}={}){const target=findSlide(entries,n)||entries[0];number=slideKey(target.slide);clock=0;sceneClock=0;scenePaused=false;liveControls.reset();last=performance.now();revealStep=reveal==='all'?revealCount():Math.max(firstBuild(current()),reveal);selected=null;mediaSignature='';history.replaceState(null,'','#'+number);const d=current();syncSlidePosition();$('#slide-title').textContent=d.title;$('#file-path').textContent='slides/'+target.file;$('#file-path').title='workstreams/talk/source/slide-studio-v005/slides/'+target.file;document.title=slideLabel(target.slide)+' · '+d.title+' — NEWHEAT';navigation();renderStage(animate);renderInspector();badges();message('');fit()}

async function refresh(){const r=await fetch('/api/slides');if(!r.ok)throw new Error('Could not load the slides');entries=(await r.json()).slides;if(!entries.length)throw new Error('No slides found')}
async function save(){if(!drafts.has(entry().slide.id)||saving)return;const id=entry().slide.id,draft=clone(drafts.get(id));try{validateSlide(draft.slide);saving=true;badges();const r=await fetch('/api/slides/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const result=await r.json();if(!r.ok)throw new Error(result.error);entries=entries.map(e=>e.slide.id===id?result:e);if(JSON.stringify(drafts.get(id))===JSON.stringify(draft))drafts.delete(id);else if(drafts.has(id))drafts.get(id).revision=result.revision;retain();navigation();message('Slide '+slideLabel(result.slide)+' saved to disk.')}catch(e){message(e.message,true)}finally{saving=false;badges()}}
function setReview(value){reviewing=presenting&&value;document.body.classList.toggle('reviewing',reviewing);scriptReview.setOpen(reviewing);$('#exit-present').setAttribute('aria-pressed',String(reviewing));const url=new URL(location.href);url.searchParams.delete('edit');if(reviewing)url.searchParams.set('script','');else url.searchParams.delete('script');history.replaceState(null,'',url.pathname+url.search+url.hash);fit();wake()}
function setPresent(value,claim=false){presenting=value;const url=new URL(location.href);url.searchParams.delete('present');url.searchParams.delete('edit');if(value)url.searchParams.delete('studio');else url.searchParams.set('studio','');history.replaceState(null,'',url.pathname+url.search+url.hash);if(value)revealStep=firstBuild(current());document.body.classList.toggle('presenting',value);$('#present-controls').hidden=!value;continuous=false;$('#continuous').setAttribute('aria-pressed','false');clock=0;if(value)resetAnimation();renderOverlays();syncAnimation();setReview(reviewing);fit();wake();presentationSync.send(claim)}
function wake(){document.body.classList.add('active');clearTimeout(wakeTimer);wakeTimer=setTimeout(()=>document.body.classList.remove('active'),2500)}
for(const name of ['camera','text','notes'])$('#'+name+'-tab').onclick=()=>{showTab(name);renderOverlays()};
$('#scene-up').onclick=$('#present-up').onclick=()=>boostScene(1);
$('#scene-down').onclick=$('#present-down').onclick=()=>boostScene(-1);
$('#prev').onclick=$('#present-prev').onclick=()=>step(-1);$('#next').onclick=$('#present-next').onclick=()=>step(1);
$('#restart-build').onclick=()=>{revealStep=firstBuild(current());if(tab==='text')showTab('camera');if(current().scene.afterMedia)renderStage(false);else syncReveals()};
$('#save').onclick=save;$('#discard').onclick=async()=>{try{const id=entry().slide.id;await refresh();drafts.delete(id);retain();go(number);message('Loaded the saved slide.')}catch(e){message(e.message,true)}};
$('#copy-link').onclick=async()=>{try{await navigator.clipboard.writeText(location.origin+'/NEWHEAT-live-deck.html#'+number);message('Link copied for slide '+slideLabel(entry().slide))}catch{message(location.origin+'/NEWHEAT-live-deck.html#'+number)}};
$('#view-type').onchange=e=>{cameraEdit(s=>{s.view.type=e.target.value;s.view.state=clone(viewDefaults[s.view.type]);if(s.view.type==='OrbitView'&&s.scene.preset==='globe')s.scene.preset='grid';if(s.view.type!=='OrbitView'&&s.scene.preset==='grid')s.scene.preset='globe'});renderInspector();renderStage()};
$('#scene-preset').onchange=e=>{cameraEdit(s=>{s.scene.preset=e.target.value;if(scenes[e.target.value].requires&&s.view.type!==scenes[e.target.value].requires){s.view.type=scenes[e.target.value].requires;s.view.state=clone(viewDefaults[s.view.type])}if(e.target.value==='grid'){s.view.type='OrbitView';s.view.state=clone(viewDefaults.OrbitView)}if(e.target.value==='globe'&&s.view.type==='OrbitView'){s.view.type='GlobeView';s.view.state=clone(viewDefaults.GlobeView)}});renderInspector();renderStage()};
$('#reset-camera').onclick=()=>{cameraEdit(s=>{s.view=clone(entry().slide.view);if((s.scene.preset==='grid'&&s.view.type!=='OrbitView')||(s.scene.preset==='globe'&&s.view.type==='OrbitView'))s.scene.preset=entry().slide.scene.preset});renderInspector();renderStage()};
$('#apply-camera').onclick=()=>{try{const state=JSON.parse($('#camera-json').value);cameraEdit(s=>{s.view.state=state})}catch(e){message('Invalid JSON: '+e.message,true)}};
$('#background').oninput=e=>{editable().background=e.target.value;changed();$('#stage').style.background=e.target.value};
$('#duration').oninput=e=>{if(Number.isFinite(e.target.valueAsNumber)&&e.target.valueAsNumber>=1){editable().duration=e.target.valueAsNumber;changed()}};
$('#overlay-select').onchange=e=>{selected=e.target.value;syncText();renderOverlays()};
$('#add-text').onclick=()=>{const d=editable(),id='text-'+Date.now();d.overlays.push({id,text:'',x:88,y:180,width:900,size:56,font:'Roboto Black',color:'#DD9F49',align:'left'});selected=id;changed();renderInspector();renderOverlays();$('#overlay-text').focus()};
$('#remove-text').onclick=()=>{editable().overlays=editable().overlays.filter(t=>t.id!==selected);selected=null;changed();renderInspector();renderOverlays()};
$('#overlay-text').oninput=e=>{const t=editable().overlays.find(x=>x.id===selected);if(t){t.text=e.target.value;changed();renderOverlays()}};
for(const k of ['x','y','width','size','font','color','align'])$('#text-'+k).oninput=e=>{const v=['x','y','width','size'].includes(k)?e.target.valueAsNumber:e.target.value;if(typeof v==='number'&&!Number.isFinite(v))return;const d=clone(current()),t=d.overlays.find(x=>x.id===selected);if(!t)return;t[k]=v;try{validateSlide(d);editable().overlays=d.overlays;changed();renderOverlays()}catch(err){message(err.message,true)}};
$('#edit-title').oninput=e=>{editable().title=e.target.value;$('#slide-title').textContent=e.target.value;changed()};$('#notes').oninput=e=>{editable().notes=e.target.value;changed()};
for(const [id,field] of [['speaker-points','points'],['speaker-exact','text'],['speaker-mode','mode']])$('#'+id).addEventListener(id==='speaker-mode'?'change':'input',e=>{const d=editable();d.speaker??={mode:'cues',points:[]};d.speaker[field]=field==='points'?e.target.value.split('\n').map(p=>p.trim()).filter(Boolean):e.target.value;$('#speaker-exact-field').hidden=d.speaker.mode!=='exact';changed()});
$('#present').onclick=()=>setPresent(true,true);$('#exit-present').onclick=()=>setReview(!reviewing);$('#continuous').onclick=()=>{const enabled=!continuous;if(enabled&&!presenting)setPresent(true,true);continuous=enabled;clock=0;$('#continuous').setAttribute('aria-pressed',String(continuous))};
$('#cue-audio').onclick=()=>cueAudio.toggle();
$('#film-play').onclick=async()=>{const v=$('#closing-film');if(!v)return;try{cueAudio.stop();v.hidden=false;await v.play();$('#film-play').hidden=true;$('#text-layer').hidden=true}catch(e){v.hidden=true;message(e.message,true)}};
addEventListener('hashchange',()=>{go(location.hash.slice(1));presentationSync.send(true)});addEventListener('mousemove',wake);
addEventListener('keydown',e=>{if($('#phone-dialog').open)return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){if(!presenting){e.preventDefault();save();}return}if(e.metaKey||e.ctrlKey||e.altKey||(['INPUT','TEXTAREA','SELECT','VIDEO','AUDIO'].includes(e.target.tagName)||e.target.isContentEditable))return;if(renderer.playground&&globeOwnsKey(e.target,e.key))return;if(e.key==='ArrowUp'||e.key==='ArrowDown'){if(sceneActions[current()?.scene.preset]){e.preventDefault();if(!e.repeat)boostScene(e.key==='ArrowUp'?1:-1)}return}if(e.key==='Escape'&&presenting){setReview(false);return}if(e.key==='ArrowRight'||e.key==='PageDown'||(e.key===' '&&e.target.tagName!=='BUTTON')){e.preventDefault();step(1)}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();step(-1)}});
async function refreshSavedSlides(){const before=entry();await refresh();const after=entry();if(!after){go(1);return}if(!drafts.has(after.slide.id)&&before?.revision!==after.revision){go(number,{animate:false});return}navigation();badges();syncSlidePosition();syncReveals();if(drafts.has(after.slide.id)&&drafts.get(after.slide.id).revision!==after.revision)message('Saved file changed. Your draft is retained; reload saved to compare.',true)}
const events=new EventSource('/events');let connectedOnce=false;
events.onopen=async()=>{$('#connection').textContent='Dev server connected';$('#connection').className='online';if(connectedOnce&&entries.length){try{await refreshSavedSlides()}catch(e){message(e.message,true)}}connectedOnce=true};
events.onerror=()=>{$('#connection').textContent='Reconnecting…';$('#connection').className=''};
let refreshTimer;events.onmessage=e=>{const {type}=JSON.parse(e.data);if(type==='reload'){location.reload()}else if(type==='slides'){clearTimeout(refreshTimer);refreshTimer=setTimeout(async()=>{if(saving)return;try{await refreshSavedSlides()}catch(err){message(err.message,true)}},180)}else if(type==='build-error')message('Build failed. Check the dev server log.',true)};
try{await refresh();go(location.hash.slice(1)||location.pathname.match(/\/slides\/(\d+(?:\.\d+)?)/)?.[1]||1);setPresent(presenting)}catch(e){message(e.message,true)}
$('#animation-restart').onclick=resetAnimation;
$('#animation-play').onclick=()=>{scenePaused=!scenePaused;syncAnimation()};
$('#animation-time').oninput=e=>{sceneClock=e.target.valueAsNumber;scenePaused=true;liveControls.scrub(sceneClock);renderer.draw(sceneClock,liveControls.snapshot());syncAnimation()};
function tick(now){const elapsed=Math.max(0,(now-last)/1000),delta=Math.min(elapsed,.1);last=now;clock+=delta;if(!scenePaused)sceneClock+=elapsed;liveControls.tick(elapsed,sceneClock);renderer.tick(sceneClock,liveControls.snapshot());syncAnimation();const d=current();if(presenting&&continuous&&!revealCount()&&d?.duration&&clock>=d.duration&&!['film','flame','black'].includes(d.kind)&&!entry()?.optional)go(slideKey(adjacentSlide(entries,d.id,1).slide));requestAnimationFrame(tick)}requestAnimationFrame(tick);

async function showPhoneScript(){
 const dialog=$('#phone-dialog');dialog.showModal();$('#phone-copy').textContent='Copy phone link';$('#phone-link').removeAttribute('href');$('#phone-link').textContent='Connecting…';
 try{const r=await fetch('/api/phone');if(!r.ok)throw Error();const connection=await r.json();$('#phone-link').href=connection.url;$('#phone-link').textContent=connection.url.split('#')[0];$('#phone-instructions').textContent=connection.mode==='internet'?'Scan on Wi-Fi or cellular. This is your private script link.':'Join the same Wi-Fi as this Mac, then scan.';$('#phone-qr').src='/phone-qr.svg?refresh='+Date.now();}
 catch{$('#phone-link').textContent='Phone server is reconnecting. Try again in a moment.';}
}
$('#phone-script').onclick=$('#phone-script-editor').onclick=showPhoneScript;
$('#phone-close').onclick=()=>$('#phone-dialog').close();
$('#phone-copy').onclick=async()=>{try{await navigator.clipboard.writeText($('#phone-link').href);$('#phone-copy').textContent='Copied'}catch{$('#phone-copy').textContent='Use the link above'}};
